version: 1.0.{build}
image:
- Visual Studio 2013
- Visual Studio 2015
before_build:
- cmd: >-
    appveyor DownloadFile https://download.affectiva.com/windows/AffdexSDK-3.4.1-575-win64.exe -FileName AffdexSDK-win64.exe

    AffdexSDK-win64.exe /S

    nuget restore affdex-win-samples.sln
build:
  parallel: true
  verbosity: detailed
artifacts:
- path: 'bin\release'
deploy:
- provider: GitHub
  release: 3.4
  auth_token:
    secure: sjCE8t4b8ME8j2D6e0kRpNib8STOljgGVPdexj4n0gXU/nYxFkdaI9GXRukRHri5
  artifact: 'bin\release\release.zip'
